### ISSUE TITLE
Using ignite.distributed with 3 or more processes hangs indefinitely 

### ISSUE THREAD

**Issue by ivankitanovski** [pytorch/ignite#2185]
## ❓ Questions/Help/Support

Trying to use the `ignite.distributed` to train a model with DDP. The issue I encounter is that when spawning 3 or processes to run my code, it seems to hang indefinitely. Works fine with 2 processes. I even tried a very basic script and still hangs (similar to the tutorial).

```python
# run.py
import torch
import ignite.distributed as idist

def run(rank, config):
    print(f"Running basic DDP example on rank {rank}.")

def main():
    world_size = 4  # if this is 3 or more it hangs

    # some dummy config
    config = {}

    # run task
    idist.spawn("nccl", run, args=(config,), nproc_per_node=world_size)
    
    # the same happens even in this case
    # with idist.Parallel(backend="nccl", nproc_per_node=world_size) as parallel:
    #     parallel.run(run, config)

if __name__ == "__main__":
    main()
```

Executing this with:

```bash
python -m module.run
```
I'd be very grateful if anyone can weigh in on this.

## Environment

- PyTorch Version: 1.9.0
- Ignite Version: 0.4.6
- OS: Ubuntu 20.04.2 LTS
- How you installed Ignite (`conda`, `pip`, source): conda
- Python version: 3.9.6
- Any other relevant information: Running on 4 A100-PCIE-40GB GPUs

**Comment by vfdev-5** [comment]
@ivankitanovski thanks for reporting, we'll investigate what happens exactly.

Meanwhile, can you try to run the training with torch dist launcher :
```python
# run.py
import torch
import ignite.distributed as idist

def run(rank, config):
    print(f"Running basic DDP example on rank {rank}.")

def main():

    # some dummy config
    config = {}
    
    # the same happens even in this case
    with idist.Parallel(backend="nccl") as parallel:
        parallel.run(run, config)

if __name__ == "__main__":
    main()
```
```bash
# if you have 4 GPUs
python -u -m torch.distributed.launch --nproc_per_node=4 --use_env main.py
```

**Comment by ivankitanovski** [comment]
Thanks for the quick feedback @vfdev-5. I tried that and, unfortunately, it sill the same (for 3 or 4 processes). Again, tried it with 2 processes and that worked.

**Comment by sdesrozis** [comment]
@ivankitanovski Could you try using the gloo backend instead of nccl ? Thanks in advance.

**Comment by vfdev-5** [comment]
Could you please check if pytorch distributed only works with A100 on 4 gpus. Please try to run this code:
```python
# main.py
# python -m torch.distributed.launch --nproc_per_node=4 --use_env main.py

import time
import torch
import torch.distributed as dist


def pprint(rank, msg):
    # We add sleep to avoid printing clutter
    time.sleep(0.5 * rank)
    print(rank, msg)


if __name__ == "__main__":

    # you can try "gloo" as well instead of "nccl"    
    dist.init_process_group("nccl")

    rank = dist.get_rank()
    ws = dist.get_world_size()
    torch.cuda.set_device(rank)

    pprint(rank, f"Hello from process {rank} among {ws} others")
    pprint(rank, f"Group type: {type(dist.get_backend())} : {dist.get_backend()}")
    
    dist.destroy_process_group()
```

**Comment by sdesrozis** [comment]
I just tried on a cluster 8 GPUs per node using SLURM and it works fine.

**Comment by sdesrozis** [comment]
I will try asap on another machine without using the slurm configuration.

**Comment by vfdev-5** [comment]
Tested all above code snippets on 3 and 4 V100 GPUs (aws) with pytorch 1.9.0 and python 3.9 and everything works fine. Here are logs for the first code with spawn:

<details>
<summary>
Spawn on 3 GPUs
</summary>

```bash
(test) root@ip-172-31-3-32:/repro/repro-ignite-2185# python -u ignite_main_spawn.py
/opt/conda/envs/test/lib/python3.9/site-packages/torch/package/_mock_zipreader.py:17: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448255797/work/torch/csrc/utils/tensor_numpy.cpp:67.)
  _dtype_to_storage = {data_type(0).dtype: data_type for data_type in _storages}
/opt/conda/envs/test/lib/python3.9/site-packages/torch/package/_mock_zipreader.py:17: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448255797/work/torch/csrc/utils/tensor_numpy.cpp:67.)
  _dtype_to_storage = {data_type(0).dtype: data_type for data_type in _storages}
/opt/conda/envs/test/lib/python3.9/site-packages/torch/package/_mock_zipreader.py:17: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448255797/work/torch/csrc/utils/tensor_numpy.cpp:67.)
  _dtype_to_storage = {data_type(0).dtype: data_type for data_type in _storages}
/opt/conda/envs/test/lib/python3.9/site-packages/torch/package/_mock_zipreader.py:17: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448255797/work/torch/csrc/utils/tensor_numpy.cpp:67.)
  _dtype_to_storage = {data_type(0).dtype: data_type for data_type in _storages}
[W ProcessGroupNCCL.cpp:1569] Rank 0 using best-guess GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
[W ProcessGroupNCCL.cpp:1569] Rank 1 using best-guess GPU 1 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
[W ProcessGroupNCCL.cpp:1569] Rank 2 using best-guess GPU 2 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
Running basic DDP example on rank 0.
Running basic DDP example on rank 2.
Running basic DDP example on rank 1.
```

</details>


<details>
<summary>
Spawn on 4 GPUs
</summary>

```
(test) root@ip-172-31-3-32:/repro/repro-ignite-2185# python -u ignite_main_spawn.py
/opt/conda/envs/test/lib/python3.9/site-packages/torch/package/_mock_zipreader.py:17: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448255797/work/torch/csrc/utils/tensor_numpy.cpp:67.)
  _dtype_to_storage = {data_type(0).dtype: data_type for data_type in _storages}
/opt/conda/envs/test/lib/python3.9/site-packages/torch/package/_mock_zipreader.py:17: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448255797/work/torch/csrc/utils/tensor_numpy.cpp:67.)
  _dtype_to_storage = {data_type(0).dtype: data_type for data_type in _storages}
/opt/conda/envs/test/lib/python3.9/site-packages/torch/package/_mock_zipreader.py:17: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448255797/work/torch/csrc/utils/tensor_numpy.cpp:67.)
  _dtype_to_storage = {data_type(0).dtype: data_type for data_type in _storages}
/opt/conda/envs/test/lib/python3.9/site-packages/torch/package/_mock_zipreader.py:17: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448255797/work/torch/csrc/utils/tensor_numpy.cpp:67.)
  _dtype_to_storage = {data_type(0).dtype: data_type for data_type in _storages}
/opt/conda/envs/test/lib/python3.9/site-packages/torch/package/_mock_zipreader.py:17: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448255797/work/torch/csrc/utils/tensor_numpy.cpp:67.)
  _dtype_to_storage = {data_type(0).dtype: data_type for data_type in _storages}
[W ProcessGroupNCCL.cpp:1569] Rank 0 using best-guess GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
[W ProcessGroupNCCL.cpp:1569] Rank 1 using best-guess GPU 1 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
[W ProcessGroupNCCL.cpp:1569] Rank 2 using best-guess GPU 2 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
[W ProcessGroupNCCL.cpp:1569] Rank 3 using best-guess GPU 3 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
Running basic DDP example on rank 3.
Running basic DDP example on rank 0.
Running basic DDP example on rank 1.
Running basic DDP example on rank 2.
```
</details>


<details>
<summary>
nvidia-smi
</summary>

```
(test) root@ip-172-31-3-32:/repro/repro-ignite-2185# nvidia-smi
Tue Sep  7 00:11:36 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:1B.0 Off |                    0 |
| N/A   38C    P0    53W / 300W |      0MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:00:1C.0 Off |                    0 |
| N/A   37C    P0    48W / 300W |      0MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  Off  | 00000000:00:1D.0 Off |                    0 |
| N/A   39C    P0    53W / 300W |      0MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   38C    P0    56W / 300W |      0MiB / 16160MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
</details>

**Comment by vfdev-5** [comment]
@ivankitanovski can you please share more info on your infrastucture, total number of gpus available on the node. How exactly you run the code and if any logs are printed before hanging...

**Comment by ivankitanovski** [comment]
Thanks for the quick feedback again. We are working on a package (aitlas) that has multiple modules in it. I am rnning the script in the root of package with `python -m package.test`. The `package/test.py` script has the code I shared earlier. 

The server has 4 A100-PCIE-40GB GPUs. It has 2TB of RAM memory and 256 AMD EPYC 7742 64-Core Processors.

Pytorch (1.9.0) and Pytorch-ignite (0.4.6.) are installed with conda (4.9.2).   

This is appears in the logs when running:

```
(aitlas) user@kt-gpu2:~/aitlas$ python -m aitlas.test
2021-09-07 18:43:57,015 ignite.distributed.launcher.Parallel INFO: Initialized distributed launcher with backend: 'nccl'
2021-09-07 18:43:57,015 ignite.distributed.launcher.Parallel INFO: - Parameters to spawn processes:
        nproc_per_node: 4
        nnodes: 1
        node_rank: 0
2021-09-07 18:43:57,015 ignite.distributed.launcher.Parallel INFO: Spawn function '<function run at 0x7f51227a2e50>' in 4 processes
[W ProcessGroupNCCL.cpp:1569] Rank 0 using best-guess GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
[W ProcessGroupNCCL.cpp:1569] Rank 2 using best-guess GPU 2 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
[W ProcessGroupNCCL.cpp:1569] Rank 1 using best-guess GPU 1 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
[W ProcessGroupNCCL.cpp:1569] Rank 3 using best-guess GPU 3 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
```

And, it indefinetly stays in this state.

**Comment by vfdev-5** [comment]
@ivankitanovski thanks for the info. I was suspecting that if your server has more than 4 GPUs than when ignite calls barrier could freeze everything... 
Could you please also run this script to get more env info:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
Do you have any chance to check the same code on other multi-gpu machine ? I would like to understand if it is related to A100 (hardware) or software, for example if you run the same test on a clean conda env with pytorch and ignite only  ?

**Comment by ivankitanovski** [comment]
Thanks for this script. I ran it and this is the output:

```
Collecting environment information...
PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.20.4
Libc version: glibc-2.31

Python version: 3.9.6 (default, Aug 18 2021, 19:38:01)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-73-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: A100-PCIE-40GB
GPU 1: A100-PCIE-40GB
GPU 2: A100-PCIE-40GB
GPU 3: A100-PCIE-40GB

Nvidia driver version: 460.73.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] pytorch-ignite==0.4.6
[pip3] torch==1.9.0
[pip3] torchaudio==0.9.0a0+33b2469
[pip3] torchvision==0.10.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.1.1               h6406543_8    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.3.0           h06a4308_520
[conda] mkl-service               2.4.0            py39h7f8727e_0
[conda] mkl_fft                   1.3.0            py39h42c9631_2
[conda] mkl_random                1.2.2            py39h51133e4_0
[conda] numpy                     1.20.3           py39hf144106_0
[conda] numpy-base                1.20.3           py39h74d4b33_0
[conda] pytorch                   1.9.0           py3.9_cuda11.1_cudnn8.0.5_0    pytorch
[conda] pytorch-ignite            0.4.6                    pypi_0    pypi
[conda] torchaudio                0.9.0                      py39    pytorch
[conda] torchvision               0.10.0               py39_cu111    pytorch
```

Unfortunately, I don't have access to another multi-gpu machine. I have another one, which is single GPU, but that won't make sense. 

Thanks again for looking into this.

**Comment by vfdev-5** [comment]
@ivankitanovski thanks for the info. I'm really interested to understand what happens in your case on your infrastructure.
There are few things which seem a bit strange to me.
- cudatoolkit is installed from conda-forge. Technically, pytorch recommended that for v1.8.0 but for v1.9.0 they say to use `nvidia` channel.

Could you please try the following things:
1) run again your hanging script with `NCCL_DEBUG=INFO` and report the full output
```bash
NCCL_DEBUG=INFO python -m package.test
```
2) change the backend to "gloo" and run again (without `NCCL_DEBUG=INFO`)
```bash
python -m package.test
```
I think this should work

3) let's update pure pytorch code snippet from https://github.com/pytorch/ignite/issues/2185#issuecomment-913652792 as 
following:
```python
# main.py
# NCCL_DEBUG=INFO python -m torch.distributed.launch --nproc_per_node=4 --use_env main.py

import time
import torch
import torch.distributed as dist

def pprint(rank, msg):
    # We add sleep to avoid printing clutter
    time.sleep(0.5 * rank)
    print(rank, msg)

if __name__ == "__main__":

    # you can try "gloo" as well instead of "nccl"    
    dist.init_process_group("nccl")

    rank = dist.get_rank()
    ws = dist.get_world_size()
    torch.cuda.set_device(rank)

    pprint(rank, f"Hello from process {rank} among {ws} others")
    pprint(rank, f"Group type: {type(dist.get_backend())} : {dist.get_backend()}")

    pprint(rank, "Call barrier")
    dist.barrier()

    dist.destroy_process_group()
```
and run it
```bash
NCCL_DEBUG=INFO python -m torch.distributed.launch --nproc_per_node=4 --use_env main.py
```
I would expect this also to hang.

4) Optionally, if you have docker installed, let's use our prebuilt docker image to check with another software stack
```bash
docker pull pytorchignite/base:latest
# Assuming that the current folder contains your hanging script with NCCLbackend
docker run --rm -it -v $PWD:/repro -w /repro pytorchignite/base:latest /bin/bash -c "NCCL_DEBUG=INFO python -m package.test"
```


Thanks a lot for helping to debug that.

**Comment by ivankitanovski** [comment]
This did it.

> @ivankitanovski Could you try using the gloo backend instead of nccl ? Thanks in advance.

Don't _why_ I didn't try this in the first place. But, any how, it works now. Not sure, if there are major drawbacks to using this over `nccl`, but I see the GPUs are getting used and things are processed. 

Thanks for the help @vfdev-5 @sdesrozis

**Comment by vfdev-5** [comment]
Thanks for the feedback, @ivankitanovski !
I'd expect gloo a bit slower than nccl. 
For completeness sake, could you still please run above commands to understand what happened with nccl.

**Comment by vfdev-5** [comment]
Let's close this issue as resolved. @ivankitanovski feel free to reopen if needed
